
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

bot:
  token: 111